export const VIEW_DOCTORS_REQUEST = 'VIEW_DOCTORS_REQUEST';
export const VIEW_DOCTORS_SUCCESS = 'VIEW_DOCTORS_SUCCESS';
export const VIEW_DOCTORS_FAILURE = 'VIEW_DOCTORS_FAILURE';
export const VERIFY_DOCTOR_REQUEST = 'VERIFY_DOCTOR_REQUEST';
export const VERIFY_DOCTOR_SUCCESS = 'VERIFY_DOCTOR_SUCCESS';
export const VERIFY_DOCTOR_FAILURE = 'VERIFY_DOCTOR_FAILURE';
export const UNVERIFY_DOCTOR_REQUEST = 'UNVERIFY_DOCTOR_REQUEST';
export const UNVERIFY_DOCTOR_SUCCESS = 'UNVERIFY_DOCTOR_SUCCESS';
export const UNVERIFY_DOCTOR_FAILURE = 'UNVERIFY_DOCTOR_FAILURE';
export const FETCH_VERIFIED_DOCTORS_REQUEST = 'FETCH_VERIFIED_DOCTORS_REQUEST';
export const FETCH_VERIFIED_DOCTORS_SUCCESS = 'FETCH_VERIFIED_DOCTORS_SUCCESS';
export const FETCH_VERIFIED_DOCTORS_FAILURE = 'FETCH_VERIFIED_DOCTORS_FAILURE';

export const VIEW_PATIENTS_REQUEST = 'VIEW_PATIENTS_REQUEST';
export const VIEW_PATIENTS_SUCCESS = 'VIEW_PATIENTS_SUCCESS';
export const VIEW_PATIENTS_FAILURE = 'VIEW_PATIENTS_FAILURE';
export const VERIFY_PATIENT_REQUEST = 'VERIFY_PATIENT_REQUEST';
export const VERIFY_PATIENT_SUCCESS = 'VERIFY_PATIENT_SUCCESS';
export const VERIFY_PATIENT_FAILURE = 'VERIFY_PATIENT_FAILURE';
export const UNVERIFY_PATIENT_REQUEST = 'UNVERIFY_PATIENT_REQUEST';
export const   unverifyDoctorSuccess= 'UNVERIFY_PATIENT_SUCCESS';
export const unverifyDoctorFailure  = 'UNVERIFY_PATIENT_FAILURE';

export const FETCH_USER_DATA_REQUEST = 'user/fetchUserDataRequest';
export const FETCH_USER_DATA_FAILURE = 'user/fetchUserDataFailure';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'UPDATE_USER_DATA_ERROR';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
// actionTypes.js

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const COMPLETE_DETAILS_SUCCESS = 'COMPLETE_DETAILS_SUCCESS';
export const COMPLETE_DETAILS_ERROR = 'COMPLETE_DETAILS_ERROR';
export const FETCH_PATIENT_DATA_ERROR = 'FETCH_PATIENT_DATA_ERROR';
// Add more action types as needed
// ActionTypes
export const FETCH_PATIENT_DATA_REQUEST = 'FETCH_PATIENT_DATA_REQUEST';
export const FETCH_PATIENT_DATA_SUCCESS = 'FETCH_PATIENT_DATA_SUCCESS';
export const FETCH_PATIENT_DATA_FAILURE = 'FETCH_PATIENT_DATA_FAILURE';

// Action Creators
export const fetchPatientDataRequest = () => ({
  type: FETCH_PATIENT_DATA_REQUEST
});

export const fetchPatientDataSuccess = (patientData) => ({
  type: FETCH_PATIENT_DATA_SUCCESS,
  payload: patientData
});

export const fetchPatientDataFailure = (error) => ({
  type: FETCH_PATIENT_DATA_FAILURE,
  payload: error
});

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';